# H2 Database Configuration
quarkus:
  datasource:
    db-kind: h2
    jdbc:
      url: "jdbc:h2:mem:etl_cdr_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: etl_user
    password: etl_pass

    # Use our custom H2 database configuration
    devservices:
      enabled: false
  # Hibernate ORM Configuration
  hibernate-orm:
    # Configure database generation strategy
    database:
      generation: drop-and-create  # none (we use init.sql), drop-and-create, create, update

    # Use custom SQL script for initialization
    sql-load-script: init.sql

  # H2 Console Configuration
  # Use developer console to view H2 database
  dev-ui:
    enabled: true

  # Logging Configuration
  log:
    # Overall log level
    level: INFO

    category:
      # Basic SQL logging
      "org.hibernate.SQL":
        level: INFO
      # My specific logging
      "dev.nexonm":
        level: DEBUG

    # ?????????? ????? ? ???????
    console:
      enable: true
      format: "%d{HH:mm:ss} %-5p [%c{2.}.%M] (%t) %s%e%n"
      color: true
